"use client";
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { usePlantStore } from '@plantitas/core';
import { useParams } from 'next/navigation';
import { useTranslation } from 'react-i18next';
export default function PlantDetailPage() {
    const { slug } = useParams();
    const { plants, language } = usePlantStore();
    const { t } = useTranslation();
    const plant = plants.find(p => p.slug === slug);
    if (!plant)
        return _jsx("div", { className: "p-20 text-center font-black text-3xl", children: "Planta no encontrada." });
    const primaryImage = plant.images.find(img => img.isPrimary) || plant.images[0];
    const label = language === 'es' ? plant.labelES : plant.labelEN;
    return (_jsx("div", { className: "container mx-auto px-6 py-12 animate-in slide-in-from-bottom-8 duration-700", children: _jsxs("div", { className: "flex flex-col lg:flex-row gap-16 items-start", children: [_jsxs("div", { className: "w-full lg:w-1/2", children: [_jsx("div", { className: "aspect-square bg-gray-50 rounded-[3rem] overflow-hidden shadow-2xl border-8 border-white", children: _jsx("img", { src: primaryImage.url, alt: label, className: "w-full h-full object-cover" }) }), _jsx("div", { className: "grid grid-cols-4 gap-4 mt-8", children: plant.images.slice(0, 4).map((img, i) => (_jsx("div", { className: "aspect-square rounded-2xl overflow-hidden border-4 border-white shadow-md cursor-pointer hover:scale-105 transition-all", children: _jsx("img", { src: img.url, className: "w-full h-full object-cover" }) }, i))) })] }), _jsxs("div", { className: "w-full lg:w-1/2", children: [_jsxs("div", { className: "mb-10", children: [_jsx("span", { className: "text-[#2d6a4f] font-black uppercase tracking-[0.3em] text-xs mb-4 block", children: language === 'es' ? `Familia ${plant.botanicalFamily}` : `Family ${plant.botanicalFamily}` }), _jsx("h1", { className: "text-6xl md:text-8xl font-black text-[#1b4332] mb-4 tracking-tighter", children: label }), _jsx("p", { className: "text-2xl italic text-gray-400 font-medium", children: plant.scientificName })] }), _jsxs("div", { className: "flex flex-wrap gap-3 mb-12", children: [plant.facets.habitat.map(h => (_jsx("span", { className: "bg-[#2d6a4f] text-white px-4 py-2 rounded-xl text-xs font-black uppercase tracking-widest", children: h }, h))), plant.facets.use.map(u => (_jsx("span", { className: "bg-[#a0522d] text-white px-4 py-2 rounded-xl text-xs font-black uppercase tracking-widest", children: u }, u)))] }), _jsx("div", { className: "prose prose-xl text-[#1b4332] opacity-80 mb-12 leading-relaxed font-medium", children: language === 'es'
                                ? `Aprende cómo cultivar y cuidar ${plant.commonName} (${plant.labelES}) en Costa Rica.`
                                : `Learn how to grow and care for ${plant.commonName} (${plant.labelEN}) in Costa Rica.` }), _jsxs("div", { className: "grid grid-cols-1 md:grid-cols-2 gap-12", children: [_jsxs("div", { children: [_jsx("h3", { className: "text-2xl font-black mb-6 text-[#1b4332]", children: t('care.tips', 'Consejos de cuidado') }), _jsx("ul", { className: "space-y-4", children: (language === 'es' ? plant.careTipsES : plant.careTips).map((tip, i) => (_jsxs("li", { className: "flex gap-4 items-start", children: [_jsx("span", { className: "text-[#2d6a4f] text-xl", children: "\u2022" }), _jsx("span", { className: "font-bold text-gray-600 leading-snug", children: tip })] }, i))) })] }), _jsxs("div", { children: [_jsx("h3", { className: "text-2xl font-black mb-6 text-[#c0392b]", children: t('care.warnings', 'Advertencias') }), _jsx("ul", { className: "space-y-4", children: (language === 'es' ? plant.warningsES : plant.warnings).map((w, i) => (_jsxs("li", { className: "flex gap-4 items-start", children: [_jsx("span", { className: "text-[#c0392b] text-xl", children: "\u2022" }), _jsx("span", { className: "font-bold text-gray-600 leading-snug", children: w })] }, i))) })] })] }), _jsxs("div", { className: "mt-16 p-8 bg-white rounded-3xl border border-gray-100 flex items-center justify-between", children: [_jsxs("div", { children: [_jsx("p", { className: "text-sm font-bold text-gray-400 mb-1", children: t('care.difficulty', 'Dificultad') }), _jsx("p", { className: "text-xl font-black text-[#1b4332] uppercase tracking-wider", children: plant.difficultyLevel })] }), _jsx("button", { className: "bg-[#1b4332] text-white px-10 py-5 rounded-2xl font-black text-lg hover:scale-105 transition-all shadow-xl", children: t('common.addToCollection', 'Añadir a mi colección') })] })] })] }) }));
}
